spring:
  application:
    name: mod7

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/task_db?authSource=admin

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration