server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:6432/data_contact
    username: postgres
    password: postgres